name: CD - Release

on:
  release:
    types:
      - created

env:
  IMAGE: indeedhat/request-logger
  TAG: ${{ github.event.release.tag_name }}
  REGISTRY_HOST: ghcr.io

jobs:
  package:
    timeout-minutes: 6
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: ${{ env.REGISTRY_HOST }}/${{ env.IMAGE }}:${{ env.TAG }}
